export const APP_SECRET = "this is a secret"

export const GAME_CONFIG = {
    POPULATION_GROWTH: 500,
    MAX_POPULATION: 5000,
    INCOME_CITY: 100,
    INCOME_COASTAL: 2000,
    INCOME_INDUSTRIAL: 500,
    FOOD_GROWN: 200,
    FOOD_LOST: 50,
    NEW_TROOPER: 100,
    NEW_TURRET: 15,
    NEW_BOMBER: 5,
    NEW_TANK: 10,
    NEW_CARRIER: 2,
    TAX_REQ: 5,
    ARMY_FOOD_REQ: 10,
    PEOPLE_FOOD_REQ: 5
}

export const TURN_CONFIG = {
    START: 0,
    PAYMENT: 1,
    BUILD: 2
}